# This is a basic workflow to help you get started with Actions

name: checkUWOshWIP

# Controls when the workflow will run
  on:
    schedule:
      - cron: '25 * * * *'
    push:
      branches: [ "main" ]
      
jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
    - name: testing
      uses: actions/checkout@v2 
    - name: Run Script
      run: |
        echo "is this doing anything?"
